jwt:
  # Base64로 32바이트(이상) 키를 넣는 것을 권장
  secret: ${JWT_SECRET:ZmFrZS1kZXYtc2VjcmV0LWZvci1sb2NhbC10ZXN0LXNob3VsZC1iZS1iYXNlNjQ=}
  issuer: wewha
  access-exp-seconds: 3600
  refresh-exp-seconds: 1209600
