spring:
  application:
    name: wewha

  datasource:
    url: jdbc:mysql://wewhadb.c12wo6kwwlq2.ap-northeast-2.rds.amazonaws.com:3306/wewhaDB?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: ewha1886!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      max-lifetime: 1800000     # 30m
      idle-timeout: 600000      # 10m
      keepalive-time: 300000    # 5m
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_spl: true

  security:
    user:
      name: admin
      password: 1234

jwt:
  secret: MySuperSecretKeyThatIsAtLeast32Bytes!

server:
  port: 8080